"""Generate `REFERENCE.md` -- the game's data dictionary -- from the registries.

Every catalog in the codebase already carries its own player-facing text: an
`Ability`/`Talent` has a `name` and an `effect`, `data.RACES`/`OCCUPATIONS` are
tables, `world.ARENA_TIERS` are `Bout`s. This walks those and emits one Markdown
reference so nobody hand-maintains a second copy that drifts.

    python -m gartok.reference           # (re)write REFERENCE.md
    python -m gartok.reference --check    # exit 1 if REFERENCE.md is stale

`test_reference.py` runs the `--check` in the suite, so adding an ability or an
item without regenerating fails CI. The prose ruleset (`RULES.md`) is written by
hand and points here for the numbers.
"""

import sys
from pathlib import Path

from . import abilities, data, economy, factions, hunt, progression, talents, world

REFERENCE_PATH = Path(__file__).resolve().parent.parent / "REFERENCE.md"

_BANNER = (
    "<!-- GENERATED by `python -m gartok.reference` from the code registries.\n"
    "     Do not edit by hand: change the table/registry in `gartok/` and "
    "regenerate. -->"
)


def _dice(n, faces):
    return f"{n}d{faces}"


def _table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def _races():
    rows = []
    for r in (data.race_by_name(n) for n in data.RACE_NAMES):
        s = r["mods"]
        mods = " ".join(f"{v:+d}" for v in s)
        rows.append((r["name"], mods, f"d{r['hd']}", r["size"], r["language"],
                     f"{r['age_mult']:g}x", abilities.get(r["ability"]).name))
    head = ("Race", "STR DEX CON INT WIS CHA", "Hit Die", "Size", "Language",
            "Age", "Ability")
    return "## Races\n\nAttribute rolls are 3d6; the modifiers below are added " \
           "after.\n\n" + _table(head, rows)


def _abilities():
    rows = [(a.name, a.effect) for a in abilities.ABILITIES.values()]
    return "## Racial abilities\n\nThe generator kept only the names; every " \
           "effect below was designed for the wargame.\n\n" \
           + _table(("Ability", "Effect"), rows)


def _occupations():
    rows = [(o[1], o[2], o[3]) for o in data.OCCUPATIONS]
    return "## Occupations\n\nEach occupation grants one starting weapon and one " \
           "starting item.\n\n" + _table(("Occupation", "Weapon", "Item"), rows)


def _weapons():
    rows = []
    for name, w in data.WEAPONS.items():
        rng = "melee" if w["range"] == 0 else f"{w['range']} sq"
        thrown = "--" if w["thrown"] == 0 else f"{w['thrown']} sq"
        rows.append((name, _dice(*w["damage"]), rng,
                     "yes" if w["finesse"] else "--", thrown, w["hands"],
                     f"{w['weight']:g} kg", economy.PRICES.get(name, "--")))
    head = ("Weapon", "Damage", "Range", "Finesse", "Thrown", "Hands", "Weight",
            "Price (cp)")
    return "## Weapons\n\n" + _table(head, rows)


def _armor():
    rows = []
    for name, a in data.ARMOR.items():
        cap = "--" if a["max_dex"] is None else f"+{a['max_dex']}"
        spd = "--" if a["speed"] == 0 else f"-{a['speed']} sq"
        rows.append((name, f"+{a['ac']}", cap, spd, f"{a['weight']:g} kg",
                     economy.PRICES.get(name, "--")))
    head = ("Armor", "AC", "Max DEX to AC", "Speed", "Weight", "Price (cp)")
    return "## Armor\n\n" + _table(head, rows)


def _items():
    rows = []
    for name, wt in sorted(data.ITEM_WEIGHTS.items()):
        tags = []
        if name in data.FOOD_ITEMS:
            tags.append("food")
        if name in data.CONSUMABLE_ITEMS:
            tags.append("consumable")
        if name in data.LIGHT_SOURCES:
            tags.append(f"light {data.LIGHT_SOURCES[name]} sq")
        rows.append((name, f"{wt:g} kg", ", ".join(tags) or "--"))
    return "## Items\n\nPack items and their weights. Weapons and armor weigh " \
           "the same stowed as worn.\n\n" + _table(("Item", "Weight", "Notes"), rows)


def _sizes():
    rows = [(name, f"{s['speed']:g} m ({data.squares(s['speed'])} sq)",
             f"x{s['carry']:g}", f"{s['footprint']}x{s['footprint']}",
             _dice(*data.UNARMED_ATTACK[name]))
            for name, s in data.SIZES.items()]
    head = ("Size", "Speed", "Carry mult.", "Footprint", "Unarmed")
    return "## Sizes\n\nBase speed does not change with size; a Large creature " \
           "moves like a Medium one.\n\n" + _table(head, rows)


def _alignments():
    lines = "\n".join(f"- {name}" for _, name in data.ALIGNMENTS)
    return "## Alignments\n\nTwo axes -- order (Lawful/Neutral/Chaotic) and " \
           "morality (Good/Neutral/Evil).\n\n" + lines


def _talent_trees():
    out = ["## Talent trees\n\nOne tree per track. A new level in a track grants "
           "one pick in its tree; `requires` gates the deeper nodes. The racial "
           "track's level is `combat + work` on a scale "
           "(`progression.RACIAL_XP_THRESHOLDS`); its nodes are race-gated."]
    for track in talents.TRACKS:
        racial = track == "racial"
        head = ("Tier", "Talent", "Effect", "Requires") + (("Race",) if racial else ())
        rows = [(t.tier, t.name, t.effect, t.requires or "--")
                + ((t.race or "any",) if racial else ())
                for t in talents.TREE[track]]
        out.append(f"### {track.capitalize()} track\n\n" + _table(head, rows))
    return "\n\n".join(out)


def _factions():
    out = ["## Factions and deeds\n\nReputation moves only by completing deeds "
           "(one-shot achievements) -- there is no per-win grind."]
    for fid, fac in factions.FACTIONS.items():
        rows = [(d.name, d.blurb, f"+{d.rep}", d.requires or "--")
                for d in factions.DEEDS_BY_FACTION[fid]]
        body = (_table(("Deed", "Condition", "Rep", "Requires"), rows) if rows
                else "_No deeds yet -- standing with this faction does not move._")
        out.append(f"### {fac.name}\n\n{fac.blurb}\n\n" + body)
    return "\n\n".join(out)


def _arena_tiers():
    rows = [(b.name, b.rep, f"{b.entry}/fighter", b.purse, b.enemies, b.level)
            for b in world.ARENA_TIERS]
    head = ("Tier", "Reputation", "Stake", "Purse", "Opponents", "Opponent level")
    return "## Arena tiers\n\nStaked, non-lethal bouts. Unlocked by reputation " \
           "with The Pits.\n\n" + _table(head, rows)


def _constants():
    rows = [
        ("Death save", f"d20 >= {data.DEATH_SAVE_MIN}, on the {data.DYING_TURNS}rd "
         "turn while dying"),
        ("First-aid DC", f"d20 + WIS mod vs {data.FIRST_AID_DC}"),
        ("Automaton repair DC", f"d20 + INT mod vs {data.AUTOMATON_REPAIR_DC}"),
        ("First-aid kit charges", data.FIRST_AID_CHARGES),
        ("Quiver bolts", data.QUIVER_AMMO),
        ("Starvation death", f"{data.STARVATION_DEATH_DAYS} missed meals in a row"),
        ("Sight range", f"{data.SIGHT_MAX} sq along the line of sight"),
        ("Darkvision", f"{data.DARKVISION} sq"),
        ("Demoralize range", f"{data.DEMORALIZE_RANGE} sq"),
        ("Torch radius", f"{data.TORCH_RADIUS} sq"),
        ("Lantern radius", f"{data.LIGHT_SOURCES['Lantern']} sq"),
        ("Starting wealth", f"{economy.STARTING_WEALTH_DICE[0]}d"
         f"{economy.STARTING_WEALTH_DICE[1]} copper"),
        ("Resale factor", f"{economy.SELL_FACTOR:g} of buy price"),
        ("Lumber wage", f"{economy.LUMBER_WAGE} cp per {economy.LUMBER_BLOCK_HOURS} h "
         f"(level 0, bare-handed); {economy.LUMBER_WAGE_OWN_AXE} cp with your own Axe "
         f"(level {economy.LUMBER_LEVEL_OWN_AXE})"),
        ("Hunting job level", hunt.HUNT_LEVEL),
        ("Bank strongbox", f"{economy.BANK_CHEST_PRICE} cp to rent, holds "
         f"{economy.BANK_CHEST_CAPACITY} kg"),
        ("Combat XP thresholds", ", ".join(map(str, progression.COMBAT_XP_THRESHOLDS))),
        ("Work XP thresholds", ", ".join(map(str, progression.WORK_XP_THRESHOLDS))),
        ("Racial level thresholds (combat+work)",
         ", ".join(map(str, progression.RACIAL_XP_THRESHOLDS))),
    ]
    return "## Constants\n\nThe tunable knobs, from `data.py`, `economy.py` and " \
           "`progression.py`.\n\n" + _table(("Knob", "Value"), rows)


_SECTIONS = (_races, _abilities, _occupations, _weapons, _armor, _items, _sizes,
             _alignments, _talent_trees, _factions, _arena_tiers, _constants)


def build():
    """The full REFERENCE.md text."""
    body = "\n\n".join(section() for section in _SECTIONS)
    return f"# GARTOK reference\n\n{_BANNER}\n\n{body}\n"


def write(path=REFERENCE_PATH):
    Path(path).write_text(build(), encoding="utf-8")


def is_current(path=REFERENCE_PATH):
    p = Path(path)
    return p.exists() and p.read_text(encoding="utf-8") == build()


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if "--check" in argv:
        if is_current():
            print("REFERENCE.md is up to date.")
            return 0
        print("REFERENCE.md is stale -- run `python -m gartok.reference`.")
        return 1
    write()
    print(f"wrote {REFERENCE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
