"""Wilds encounter comparison: wolves, giant spiders, skeletons and bandits.

Headless AI-vs-AI. A "bandit" is the Wilds' own humanoid gang (`race_pool=None`
-- a rarity-weighted random race with a rolled job); the other three are the
authored bodies. Everything is generated by `gartok.encounters` with the Wilds'
headcount / level weights, so a pack here is a pack the player could meet.

Three questions, three sections:

  1. HEAD TO HEAD   -- same-level 3v3 squads of each kind, round robin. Which
                       body is stronger, level for level.
  2. WILDS ENCOUNTER -- a pack rolled by the Wilds rules (headcount and level
                       weights untouched) against a player party of level 0..5.
                       Win rate and losses a party can expect.
  3. LEVEL SCALING  -- the same Wilds headcount, but every body pitched at level
                       0..5, against a level-5 party (racial picks, so Rending
                       Bite / Giant Growth / Spin Web / Deft Bones come into play).

The party is always humanoid with a rolled job and its own kit -- no shop
armour -- built with `encounters.build_enemy`, so it follows the same
level / talent rules as the enemy side.

    python scripts/encounter_sim.py                  # ~300 battles per cell
    python scripts/encounter_sim.py --battles 800    # tighter numbers
    python scripts/encounter_sim.py --levels 0 3 5   # which party levels to run
    python scripts/encounter_sim.py --party 3        # party size (default 4)

Writes a text report under sim_results/ and prints it.
"""

from __future__ import annotations

import argparse
import itertools
import os
import random
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime, timezone

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from gartok import ai, data, encounters
from gartok.battle import Battle

KINDS = ("Wolf", "Giant Spider", "Skeleton", "Bandit")
STEP_GUARD = 2000
H2H_SQUAD = 3


def _pool(kind):
    if kind == "Wolf":
        return list(data.WILD_POOL)
    if kind == "Bandit":
        return None
    return [data.race_by_name(kind)]


def _party(level, size, rng):
    return [encounters.build_enemy(level, rng) for _ in range(size)]


def _fight(players, enemies):
    b = Battle(players, enemies)
    guard = 0
    while b.winner is None and guard < STEP_GUARD:
        guard += 1
        ai.take_turn(b, b.active)
    return {
        "winner": b.winner,
        "rounds": b.round_no,
        "stuck": guard >= STEP_GUARD,
        "players_alive": sum(1 for u in b.player_units if u.alive),
        "players": len(b.player_units),
    }


# --------------------------------------------------------------------------- #
# Workers (top level so a spawn pool can pickle them)                          #
# --------------------------------------------------------------------------- #

def _job(args):
    """One battle, fully described by plain data. -> (tag, result, extra)."""
    kind, seed, tag, p = args
    random.seed(seed)
    rng = random.Random(seed)
    if kind == "h2h":
        a, b, level, a_is_player = p
        squad_a = [encounters.build_enemy(level, rng, race_pool=_pool(a)) for _ in range(H2H_SQUAD)]
        squad_b = [encounters.build_enemy(level, rng, race_pool=_pool(b)) for _ in range(H2H_SQUAD)]
        players, enemies = (squad_a, squad_b) if a_is_player else (squad_b, squad_a)
        res = _fight(players, enemies)
        winner = res["winner"]
        a_won = None if winner is None else ((winner == "player") == a_is_player)
        return tag, res, {"a_won": a_won}
    if kind == "wilds":
        body, party_level, size = p
        pack = encounters.roll_pack(rng=rng, race_pool=_pool(body))
        party = _party(party_level, size, rng)
        res = _fight(party, pack)
        return tag, res, {"pack_n": len(pack),
                          "pack_lvl": sum(u.mean_level for u in pack) / len(pack)}
    body, pack_level, party_level, size = p                     # "scaling"
    n = encounters.weighted_choice(encounters.WILDS_COUNT_WEIGHTS, rng)
    pack = [encounters.build_enemy(pack_level, rng, race_pool=_pool(body)) for _ in range(n)]
    party = _party(party_level, size, rng)
    res = _fight(party, pack)
    return tag, res, {"pack_n": n}


def _body_sheet(kind, level, samples=60):
    """Average stat line of a level-`level` body of this kind."""
    rng = random.Random(7)
    random.seed(7)
    us = [encounters.build_enemy(level, rng, race_pool=_pool(kind)) for _ in range(samples)]

    def dmg(u):
        n, f = u.unarmed_damage if u.equipped_weapon is None else u.weapon["damage"]
        return n * (f + 1) / 2 + u.mod_strength

    def avg(xs):
        return sum(xs) / len(xs)

    return {"hp": avg([u.hp_max for u in us]), "ac": avg([u.ac for u in us]),
            "spd": avg([u.speed for u in us]), "dmg": avg([dmg(u) for u in us]),
            "cells": avg([u.footprint ** 2 for u in us])}


# --------------------------------------------------------------------------- #
# Aggregation                                                                  #
# --------------------------------------------------------------------------- #

class Cell:
    def __init__(self):
        self.n = self.party_wins = self.stuck = self.rounds = 0
        self.lost = self.members = self.pack_n = 0
        self.pack_lvl = 0.0
        self.a_wins = self.b_wins = 0

    def add(self, res, extra):
        self.n += 1
        self.party_wins += res["winner"] == "player"
        self.stuck += res["stuck"]
        self.rounds += res["rounds"]
        self.lost += res["players"] - res["players_alive"]
        self.members += res["players"]
        self.pack_n += extra.get("pack_n", 0)
        self.pack_lvl += extra.get("pack_lvl", 0.0)
        if extra.get("a_won") is True:
            self.a_wins += 1
        elif extra.get("a_won") is False:
            self.b_wins += 1

    @property
    def win(self):
        return 100 * self.party_wins / max(1, self.n)

    @property
    def loss_per_member(self):
        return 100 * self.lost / max(1, self.members)


def _run(jobs, workers):
    out = {}
    with ProcessPoolExecutor(max_workers=workers) as pool:
        for tag, res, extra in pool.map(_job, jobs, chunksize=16):
            out.setdefault(tag, Cell()).add(res, extra)
    return out


def build_jobs(battles, levels, size):
    jobs = []
    seed = itertools.count(1)
    for level in levels:
        for a, b in itertools.combinations(KINDS, 2):
            for i in range(battles):
                jobs.append(("h2h", next(seed), ("h2h", level, a, b),
                             (a, b, level, i % 2 == 0)))
    for party_level in levels:
        for body in KINDS:
            for _ in range(battles):
                jobs.append(("wilds", next(seed), ("wilds", party_level, body),
                             (body, party_level, size)))
    for body in KINDS:
        for pack_level in range(6):
            for _ in range(battles):
                jobs.append(("scaling", next(seed), ("scaling", body, pack_level),
                             (body, pack_level, 5, size)))
    return jobs


# --------------------------------------------------------------------------- #
# Report                                                                       #
# --------------------------------------------------------------------------- #

def _h2h_pct(cells, level, a, b):
    """% of decided battles the `a` squad won against `b`."""
    c = cells.get(("h2h", level, a, b))
    if c is not None:
        decided, won = c.a_wins + c.b_wins, c.a_wins
    else:
        c = cells[("h2h", level, b, a)]
        decided, won = c.a_wins + c.b_wins, c.b_wins
    return 100 * won / max(1, decided)


def report(cells, levels, battles, size):
    L = []
    w = L.append
    w(f"ENCOUNTER SIM  {datetime.now(timezone.utc):%Y-%m-%d %H:%MZ}   "
      f"{battles} battles/cell, party of {size}, head to head is {H2H_SQUAD}v{H2H_SQUAD}")
    stuck = sum(c.stuck for c in cells.values())
    if stuck:
        w(f"!! {stuck} battle(s) hit the step guard and were counted as not won.")
    w("")

    w("== BODY SHEETS (average of 60 built units; dmg = avg hit incl. STR) ==")
    for level in sorted({0, *levels, 5}):
        w(f"  level {level}")
        w(f"    {'kind':<13}{'HP':>6}{'AC':>6}{'spd':>5}{'dmg':>6}{'cells':>7}")
        for kind in KINDS:
            s = _body_sheet(kind, level)
            w(f"    {kind:<13}{s['hp']:>6.1f}{s['ac']:>6.1f}{s['spd']:>5.1f}"
              f"{s['dmg']:>6.1f}{s['cells']:>7.1f}")
    w("")

    w("== 1. HEAD TO HEAD  (row squad beats column squad, % of decided battles) ==")
    for level in levels:
        w(f"  level {level}")
        w("    " + " " * 13 + "".join(f"{k:>14}" for k in KINDS) + f"{'avg':>8}")
        for a in KINDS:
            vals = [_h2h_pct(cells, level, a, b) for b in KINDS if b != a]
            row = f"    {a:<13}"
            it = iter(vals)
            for b in KINDS:
                row += f"{'--':>14}" if a == b else f"{next(it):>13.0f}%"
            w(row + f"{sum(vals) / len(vals):>7.0f}%")
        w("")

    w("== 2. WILDS ENCOUNTER  (Wilds headcount + level weights; party of "
      f"{size} humans, same level for all) ==")
    w("   party wins % / party members lost % / avg rounds / avg pack size")
    w("    party lvl  " + "".join(f"{k:>26}" for k in KINDS))
    for lvl in levels:
        row = f"    {lvl:>9}  "
        for kind in KINDS:
            c = cells[("wilds", lvl, kind)]
            row += (f"{c.win:>8.0f}% /{c.loss_per_member:>4.0f}% /{c.rounds / c.n:>5.1f}"
                    f" /{c.pack_n / c.n:>4.1f}")
        w(row)
    w("")

    w(f"== 3. LEVEL SCALING  (every body at level N, Wilds headcount, vs a level-5 party of {size}) ==")
    w("   party wins % / party members lost %   -- bodies from level 5 may hold racial talents")
    w("    pack lvl   " + "".join(f"{k:>18}" for k in KINDS))
    for lvl in range(6):
        row = f"    {lvl:>8}   "
        for kind in KINDS:
            c = cells[("scaling", kind, lvl)]
            row += f"{c.win:>9.0f}% /{c.loss_per_member:>4.0f}%"
        w(row)
    return L


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--battles", type=int, default=300, help="battles per cell")
    ap.add_argument("--levels", type=int, nargs="+", default=[0, 3, 5])
    ap.add_argument("--party", type=int, default=4, help="player party size")
    ap.add_argument("--workers", type=int, default=os.cpu_count() or 2)
    args = ap.parse_args(argv)

    levels = sorted(set(args.levels) | {5})
    t0 = time.time()
    cells = _run(build_jobs(args.battles, levels, args.party), args.workers)
    lines = report(cells, levels, args.battles, args.party)
    text = "\n".join(lines) + f"\n\n({time.time() - t0:.0f}s)"
    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "sim_results")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"encounter_sim_{datetime.now(timezone.utc):%Y%m%d_%H%M%S}.txt")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text + "\n")
    print(text)
    print(f"\nwritten to {path}")


if __name__ == "__main__":
    main()
